version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    networks:
      - python-mongo-network

  python-app:
    container_name: python-app
    depends_on:
      - mongo
    build: 
      dockerfile: python-app.Dockerfile
      context: .
    restart: always
    environment:
      MONGO_URI: ${MONGO_URI}
    ports:
      - 8080:8080
    networks:
      - python-mongo-network

networks:
  python-mongo-network:
    driver: bridge
